# Generated by Django 3.0.5 on 2020-07-16 15:24

from django.db import migrations, models
import django.db.models.deletion
from comum.models import Lamp


def insert_lamps(apps, schema_editor):
    Lamp.objects.bulk_create([Lamp(name="Lamp 1"),
                              Lamp(name="Lamp 2"),
                              Lamp(name="Lamp 3"),
                              Lamp(name="Lamp 4"),
                              Lamp(name="Lamp 5"),
                              Lamp(name="Lamp 6")]
                             )


class Migration(migrations.Migration):
    dependencies = [
        ('comum', '0003_lamp_userlamp'),
    ]

    operations = [
        migrations.RunPython(insert_lamps),
    ]
