# Generated by Django 3.1.3 on 2020-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_insert_lamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('position', models.CharField(max_length=6)),
            ],
        ),
    ]
