# Generated by Django 3.1.3 on 2020-12-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alarm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
