# Generated by Django 3.1.3 on 2020-12-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_delete_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('speed', models.CharField(max_length=3)),
            ],
        ),
    ]
